### ISSUE TITLE
Can you please update the documentation?

### ISSUE THREAD

**Issue by suleyth** [kotlin-graphics/imgui#113]
I can only explain my issues as https://github.com/kotlin-graphics/imgui/wiki/Using-libGDX being outdated.

* `LwjglGlfw` and `ImplGL3` don't have any `INSTANCE` members.
* Nothing about the docs say you have to install uno-sdk.
* And even once installed, it says `GlfwWindow(long)` (the constructor of the class with the window handle) is private.
* `GlfwWindow(GlfwWindowHandle)` is public, but `GlfwWindowHandle(long)` doesn't exist. How do you initialize the window?
* `LwjglGlfw.init()` doesn't even exist.

So what you *actually* have to do is something like this:
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics;
import com.badlogic.gdx.graphics.GL20;
import glm_.vec2.Vec2i;
import imgui.Context;
import imgui.ImGui;
import imgui.impl.ImplGL3;
import imgui.impl.LwjglGlfw;
import uno.glfw.GlfwWindow;
import uno.glfw.GlfwWindowHandle;

public class Game extends ApplicationAdapter {
    private GlfwWindow window;
    private LwjglGlfw lwjglGlfw;
    private ImplGL3 implGL3;
    private ImGui imGui = ImGui.INSTANCE;
    private Context context;

    @Override
    public void create() {
        window = new GlfwWindow(((Lwjgl3Graphics) Gdx.graphics).getWindow().getWindowHandle());
        // What does the Vec2i param do?
        lwjglGlfw = new LwjglGlfw(window, true, LwjglGlfw.GlfwClientApi.OpenGL, new Vec2i());
        implGL3 = new ImplGL3();
        context = new Context(null);

        imGui.styleColorsDark(null);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        lwjglGlfw.newFrame();

        imGui.begin("Demo_0", new boolean[]{true}, 0);
        imGui.text("Hello, world!");
        imGui.end();

        imGui.showDemoWindow(new boolean[]{true});

        imGui.render();
        implGL3.renderDrawData(imGui.getDrawData());
    }

    @Override
    public void dispose() {
        lwjglGlfw.shutdown();
        context.shutdown();
    }
}
```

And yet that still doesn't work because the `GlfwWindow` constructor with the `long` handle is private for some reason. Is there something I'm missing?

**Comment by elect86** [comment]
> I can only explain my issues as https://github.com/kotlin-graphics/imgui/wiki/Using-libGDX being outdated.

Yep, you are right

>     * `LwjglGlfw` and `ImplGL3` don't have any `INSTANCE` members.

They are full valid classes now

>     * Nothing about the docs say you have to install uno-sdk.
 
No, it's true

>     * And even once installed, it says `GlfwWindow(long)` (the constructor of the class with the window handle) is private.
>
>     * `GlfwWindow(GlfwWindowHandle)` is public, but `GlfwWindowHandle(long)` doesn't exist. How do you initialize the window?

The constructor uses an inline class, which is still yet to come on java (Panama Project) and there is at the moment no compatibility from Kotlin side.

For this very reason, you have a static `GlfwWindow.from(long)` 
 
>     * `LwjglGlfw.init()` doesn't even exist.

No, it's been refractored in the process of matching closely the original library


Anyway, this should pretty much underline that I alone have not the financial, time and working resources at all as the original author(/s, because right now they are even multiple people) of the library.

That's why I'm totally open to contributions and most of the time I try to tempt people to jump in and give a hand, like in your case :)  (I'll send you right away an invite to join the repo)

Feel free to close if you repute it ok

**Comment by suleyth** [comment]
Sorry, I don't really have the time, and I don't really know Kotlin or this library much, so I don't think I would help. I'll look for someone who can.
