### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by pepmortem14** [kotlin-graphics/imgui#37]
After some days of porting my application to the latest LWJGL version, I tried to use Dear ImGui with it.
I got a bit confused since in the readme it says you only have to initialize elements and render them, but in the tests of the wiki you are using your own GlfwWindow, and this makes it hard for me since I need a way to port my original glfw window, as a long, to the GlfwWindow.

My code is here:
```
@Override
 public void drawScreen(int mouseX, int mouseY, float partialTicks) {
        ImGui.INSTANCE.newFrame();

        float[] f = {0f};
        int[] i = {0};

        ImGui.INSTANCE.text("Hello, world %d", 123);

        if (ImGui.INSTANCE.button("OK", new Vec2(20, 20))) {
            System.out.println("OK Button Pressed!");
        }

        ImGui.INSTANCE.sliderFloat("float", f, 0f, 1f, "display format", 0.5f);
        ImGui.INSTANCE.sliderInt("int", i, 0, 100, "display format");

        ImGui.INSTANCE.render();
    }
```
The exception being thrown is here:
```
java.lang.NullPointerException: Rendering screen
	at imgui.ImguiKt.getG(imgui.kt:22)
	at imgui.imgui.imgui_main$DefaultImpls.newFrame(main.kt:47)
	at imgui.ImGui.newFrame(imgui.kt:44)
	at <REDACTED>.ClickGUIScreen.drawScreen(ClickGUIScreen.java:61)
```

**Comment by elect86** [comment]
Well, given the continuous development, it's easy for the wiki to go out of sync with the actual code..

`GlfwWindow` is just a wrapping class built around the `long handle` to enhance and easier the glfw usage, with some code boilerplate reduction.

There is `GlfwWindow` constructor dedicated to this use case, where you have already a glfw window. In this case, you just create a "dummy" `GlfwWindow` passing the handle.

Instead of [this](https://github.com/kotlin-graphics/imgui/blob/master/src/test/kotlin/imgui/test%20lwjgl.kt#L35):

`window = GlfwWindow(1280, 720, "ImGui Lwjgl OpenGL3 example")`

You shall simply do:

`window = GlfwWindow(handle)`

Nothing more.. is this really inconvenient and hard?

If you point me the part of the wiki which you found confusing I may re-work it to make it clearer.

Follow the tests:
- create a context, init the lwjgl implementation and choose a style ([here](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L31-L37))
- in the loop, at the begin poll the events and call `newFrame()`, like [here](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L101-L102), and at the end render the gui like [here](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L143-L144)
- then at the end of your application you should clean up, but it's not mandatory

let me know :)

**Comment by pepmortem14** [comment]
I did it, but I'm getting another exception:
```
java.lang.NullPointerException: Rendering screen
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at gln.program.Program.createShader(program.kt:176)
	at gln.program.Program.<init>(program.kt:103)
	at imgui.impl.LwjglGL3$ProgramA.<init>(LwjglGL3.kt:262)
	at imgui.impl.LwjglGL3.createDeviceObjects(LwjglGL3.kt:187)
	at imgui.impl.LwjglGL3.newFrame(LwjglGL3.kt:133)
	at <REDACTED>.ClickGUIScreen.drawScreen(ClickGUIScreen.java:85)
```

My code:
```
public void setup(int windowHandle) {//Called at init
        this.mc = minecraft;
        this.window = new GlfwWindow(windowHandle);
        this.context = new Context(null);

        this.glfw.init();
        this.window.makeContextCurrent();
        this.imgui.styleColorsDark(null);
    }

    public void close() {//Called after the game loop
        this.lwjglGL3.shutdown();
        ContextKt.destroy(this.context);
        this.glfw.terminate();
    }

    public void draw() {
        this.lwjglGL3.newFrame(); //Exception goes here

        float[] f = {0f};
        int[] i = {0};

        this.imgui.text("Hello, world %d", 123);

        if (this.imgui.button("OK", new Vec2(20, 20))) {
            System.out.println("OK Button Pressed!");
        }

        this.imgui.sliderFloat("float", f, 0f, 1f, "display format", 0.5f);
        this.imgui.sliderInt("int", i, 0, 100, "display format");

        this.imgui.render();
        this.lwjglGL3.renderDrawData(this.imgui.getDrawData());
    }
```

**Comment by pepmortem14** [comment]
Now I tried calling getTexDataXXXX and for both methods I get this exception:

```
java.lang.NoSuchMethodError: org.lwjgl.stb.STBRPRect.was_packed()I
	at imgui.stb.ExtensionsKt.getWasPacked(extensions.kt:14)
	at imgui.FontAtlas.buildPackCustomRects(font.kt:821)
	at imgui.FontAtlas.buildWithStbTrueType(font.kt:633)
	at imgui.FontAtlas.build(font.kt:243)
	at imgui.FontAtlas.getTexDataAsAlpha8(font.kt:252)
	at <REDACTED>.ClickGUIScreen.drawScreen(ClickGUIScreen.java:110) <- line where I call the method
```

**Comment by elect86** [comment]
If you already initialize glfw by yourself somewhere else in your program, then you don't need to call these two lines:

```
        this.glfw.init();
        this.window.makeContextCurrent();
```

The new exception has to do with the shader creation. I have no idea why it's failing on your pc, however in one of the last commits, I do not load them anymore from `File`, rather directly from `String`

Try then to pull the very last commit

**Comment by pepmortem14** [comment]
I updated to the latest beta now.
Also, the error happens because I'm using latest lwjgl-stb (3.1.6) and the `wasPacked` method is a boolean, instead of int

**Comment by pepmortem14** [comment]
I downgraded to LWJGL 3.1.5, but it would be nice if support for latest version is added.
The GUI is fully working now, but I had to create 2 wrapper classes (for LwjglGL3 and program) since ClassLoader#getResourceAsStream doesn't work in my environment.
But now, when I run the setup method, any other input when the GUI isn't being rendered is cancelled. Any tips? My code is the same as before.

**Comment by inf0rm4tik3r** [comment]
Using the initialization code referenced [here](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L31-L37) and using
`lwjglGL3.init(new GlfwWindow(myGLFWWindowHandle), true);`
just leaves me with an AssertionError...

`Exception in thread "main" java.lang.AssertionError: Invalid displaySize value`
`	at imgui.imgui.imgui_main$DefaultImpls.newFrame(main.kt:49)`
`	at imgui.ImGui.newFrame(imgui.kt:44)`

when calling `imgui.newFrame();`.

Turning off assertions leads to an IndexOutOfBounds exception..
