### ISSUE TITLE
Using libGDX

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#4]
Hi, I can't find a way to make this library work with libGDX (which also allows to use LWGL3). 
Thank you for your help.

**Comment by elect86** [comment]
Hi Catvert,

are you working on an open source project I may clone and check that out?

**Comment by Catvert** [comment]
Yes, you can try it with: https://github.com/Catvert/Platform-Creator. Normally, it should have no problem configuring the project.

**Comment by elect86** [comment]
Ok, cloned and synced. Can you introduce me a little about structure or point me toward one main class to run?

**Comment by Catvert** [comment]
Yes of course, after importing it as a gradle project, you should have 4 modules (Platform-Creator, core, desktop and lwjgl3). There are 2 main class, for both backends(lwgl2 -> DesktopLauncher, lwgl3 -> Lwgl3Launcher). The game class is in the core module, PCGame. Thanks you for your help ! :)

**Comment by Catvert** [comment]
If you're using Intellij Idea, you can open the gradle tool window in View -> Tool Window -> Gradle. With this window, so you can refresh the project to make sure that gradle has downloaded all dependencies.
To create the run configuration, create a new Application configuration then select for the main class DesktopLauncher or Lwgl3Launcher. And for the module, desktop_main or lwjgl3_main.

**Comment by Catvert** [comment]
Hi, sorry to ask this, but I would like to know if you are working on a wrapper for libGDX? I can help if you want to, I think it might be a good idea given the number of libGDX users. Thank you very much.

**Comment by TTSKarlsson** [comment]
@Catvert , What is your error when you use the Lwjgl3Launcher with imgui?

I had to add the same run configuration as in your desktop project
`run {
    setWorkingDir(workingDir.absolutePath + "/../")
    ignoreExitValue = true
}`
or it wouldn't find the assets. But after that it runs the app under Lwjgl3 just fine.

When you add imgui you'll also need to add `maven { url "https://dl.bintray.com/kotlin/kotlin-dev" }` to your buildscript repositories because imgui's dependencies still bundles kotlin future runtimes and compiles against the experimental/alpha/beta branch of kotlin. You'll get some warnings as kotlin is explicitly not future compatible.

There is a kotlin-stable branch of imgui, but the other jitpack dependencies has not gotten similar treatment just yet, an open issue about this is pending.

I hope this helps, and please tell us if you get it working or if not. If you don't, and still want to, please create and push a branch to your repo with your attempted code of imgui and I will try to take a look at it as I'm used to the libGDX structure.

**Comment by Catvert** [comment]
Hi @TTSKarlsson, I have no problem adding Imgui to my project but I can't configure Imgui from imgui. impl. LwjglGL3 because it seems to me that this implementation uses uno-sdk. It is therefore impossible for me to "pass" the libGDX window to the LwjglGL3 init method (which requires a GlfwWindow). Do I need to recreate a new implementation for libGDX based on this one?

**Comment by TTSKarlsson** [comment]
I'm new with imgui too and am only helping with keeping the stable branch updated, but I felt I could possibly help because I know some things about libGDX.

I tried it out now and I see now, it creates its own window instead of integrating into an existing gl/glfw context. I'll see the coming week if I can fork this and create a integrating GlfwWindow if @elect86 hasn't already done something similar by then.

Lwjgl3 uses glfw, so it should work fine in GDX too, but there is more to it than just a a window handle as GlfwWindow also takes it upon itself to manage the glfw lifetime, which it can't be allowed to do if we want it to be possible to integrate it into an existing context.

if you want to try something yourself in the mean, you can get the Lwjgl3Window with
```
(Gdx.graphics as Lwjgl3Graphics).window
```
It has a private field `Long windowHandle` (that you can reach by reflection) that holds the glfw window handle.

**Comment by elect86** [comment]
Quick info, I'm trying to substitute the all the queries to the `windowHandle: Long` with others to `Gdx.graphics`.. I'll see and let you know where I will end up

**Comment by elect86** [comment]
Ok, it should work [now](https://github.com/Catvert/Platform-Creator/pull/1)

I tried first to make it work by substituting completely the uno `GlfwWindow` with single manual calls to `Gdx.graphics`

Then it was too messy/shitty, I reverted and tried to obtain that damned windowHandle because I had one hope, to init `GlfwWindow` by that..

It helped a lot @TTSKarlsson tips (also his stackoverflow question)

One last obstacles was that I couldn't retrieve a private field or a package-only method, google helped and I just had to make it accessible before [retrieving](https://github.com/elect86/Platform-Creator/blob/master/core/src/main/kotlin/be.catvert.pc/PCGame.kt#L175)

I modified then `GlfwWindow` accordingly to offer a constructor starting from the pure handler..

Another one last obstacles, I discovered I couldn't load the imgui shaders with the simple `getSystemResource`, I needed the bloody [`asStream`](https://github.com/kotlin-graphics/gln/commit/1ed02708a4171bdd79b379debf44cb85ce89d0bb)

Packed all the shits together, thanks god worked.. (coz also I didnt have more time)

@Catvert, would be nice if you could spend some time expanding the readme and writing about it, in order to help people seeking the same

**Comment by TTSKarlsson** [comment]
Nice to see it came to a solution, and clever constructor work there @elect86 ! =)

**Comment by elect86** [comment]
Small update: I pulled libgdx to make `Lwjgl3Window.getWindowHandle()` as `public` and avoiding in this way to use reflection to retrieve it.

It's been right now [merged](https://github.com/libgdx/libgdx/pull/4980#event-1338264141) by tom, we should change that as soon as the next release comes out.

The first one who remembers that (maybe you can keep an eye on that, @Catvert?) can do that :)

**Comment by Catvert** [comment]
Wow, your solution works perfectly! Thank you very much, I will explain in the readme how to set up imgui with libGDX :) (I don't speak English very well but I will try to do my best).

**Comment by Catvert** [comment]
@elect86 Can I create a page in the wiki to explain how to configure imgui with libGDX? I think it might be clearer.

**Comment by elect86** [comment]
You are welcome, Catvert :)

Sure, what you think works best. I'm not an english native as well but I might take a look at that if you want, when you are done
