### ISSUE TITLE
Broken dependencies adding imgui to a minecraft project

### ISSUE THREAD

**Issue by zeroeightysix** [kotlin-graphics/imgui#96]
I'm trying to create a [fabric](https://github.com/FabricMC/fabric) (minecraft mod environment) mod for minecraft (which uses LWJGL 3.2.1), using [fabric's example mod build.gradle](https://github.com/FabricMC/fabric-example-mod/blob/master/build.gradle).

I'd like to add imgui as a library. However, adding it to the `dependencies` task like so:
```gradle
implementation "com.github.kotlin-graphics:imgui:fc9aad3de1"
```
Will result in a lot of broken dependencies (all LWJGL):
![image](https://user-images.githubusercontent.com/27009727/58593988-ba964580-826c-11e9-950b-6b8224c84238.png)
(These show up as "`FAILED`" in the output of the `dependencies` task)

I presume this is because of the version mismatch between imgui (3.2.2) and minecraft (3.2.1) but, assuming LWJGL uses SemVer, both should be compatible, and we already have LWJGL in our classpath, so I assumed it was safe to exclude LWJGL from imgui:

```gradle
implementation("com.github.kotlin-graphics:imgui:fc9aad3de1") {
    exclude group: "org.lwjgl"
}
```
Which, indeed, made the library resolveable:
![image](https://user-images.githubusercontent.com/27009727/58594272-6475d200-826d-11e9-971b-bc57bf496612.png)

Though, actually using it will yield a NoClassDefFoundError:
```java
private static uno.glfw.glfw glfw = uno.glfw.glfw.INSTANCE;
private static ImGui imgui = ImGui.INSTANCE;
private static ImplGL3 implGl3;

static {
    glfw.init();
    implGl3 = new ImplGL3(); // Exception is thrown here
}
```
```
...
[00:08:30] [main/INFO]: [STDOUT]: java.lang.NoClassDefFoundError: gln/identifiers/GlProgram
[00:08:30] [main/INFO]: [STDOUT]: 	at imgui.impl.ImplGL3.<init>(ImplGL3.kt:39)
...
```
Looking up where `gln.identifiers.GlProgram` might come from on google, I can only find this repository. What am I doing wrong? Sorry if this is a duplicate of #42.

Thank you in advance.

**Comment by Sylvyrfysh** [comment]
Hi!

We just went to a multi-project structure in order to allow for multiple rendering backends, and this problem looks related, but I'm not entirely sure what the issue is. My best guess would be that if you are using OpenGL, you should use this code for the ImGui dependency:

`
implementation("com.github.kotlin-graphics.imgui:imgui-gl:fc9aad3de1") {
    exclude group: "org.lwjgl"
}
`

This will grab the OpenGL branch and everything that it requires, which may fix your problem. If it doesn't, let em know and we'll try some other stuff.

On a side note, LWJLGL does not strictly follow SemVer, so code may break doe to the version difference. I've considered adding LWJGL version checks to use the proper code paths on load, but so far it hasn't seemed worth it.

**Comment by zeroeightysix** [comment]
Yup, that did the trick. Thank you!

**Comment by elect86** [comment]
@Sylvyrfysh , may it be worth adding that snippet in the README?

**Comment by Sylvyrfysh** [comment]
Yeah, I'll put it in the readme
